title: JobScraPy
description: Using Python to increase job application efficiency
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: C. Reimer
repo_url: "https://github.com/carlosperate/jekyll-theme-rtd"
search_enabled: true
