title: JobScraPy
description: Using Python to increase job application efficiency
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: C. Reimer
repo_url: "https://github.com/CJBR-97/JobScraPy"
search_enabled: true
edit_on_github: true
github_docs_folder: true
#logo: 'https://your.url/image.png'
#site_favicon: 'https://your.url/here.ico'
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
google_analytics_anonymize_ip: true
hljs_style: github-gist
